// app/src/components/Editor/DataSourcePanel.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Plus, Play, CheckCircle, AlertCircle, Save, X, Database } from 'lucide-vue-next'
import { useDataSourceStore } from '@/stores/dataSource'
import { DataSourceType, type ApiDataSourceConfig, type DataSource } from '@/types/dataSource'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

const dataSourceStore = useDataSourceStore()
const isAddingSource = ref(false)
const newSourceName = ref('')
const newSourceUrl = ref('https://jsonplaceholder.typicode.com/users')
const testResult = ref<any | null>(null)
const testStatus = ref<'idle' | 'loading' | 'success' | 'error'>('idle')

async function handleTestApi() {
  if (!newSourceUrl.value) return
  testStatus.value = 'loading'
  testResult.value = null
  try {
    const response = await fetch(newSourceUrl.value)
    const data = await response.json()
    testResult.value = data
    testStatus.value = 'success'
  } catch (error) {
    testResult.value = { error: 'Failed to fetch' }
    testStatus.value = 'error'
  }
}

function handleSaveSource() {
  if (!newSourceName.value || !newSourceUrl.value) return
  const newSource: Omit<DataSource, 'id'> = {
    name: newSourceName.value,
    type: DataSourceType.API,
    config: {
      url: newSourceUrl.value,
      method: 'GET',
      params: {},
      headers: {},
    },
    data: testResult.value,
  }
  dataSourceStore.addDataSource(newSource)
  // Reset Form
  isAddingSource.value = false
  newSourceName.value = ''
  newSourceUrl.value = 'https://jsonplaceholder.typicode.com/users'
  testResult.value = null
  testStatus.value = 'idle'
}

async function handleRunSource(source: DataSource) {
  if (source.type === DataSourceType.API) {
    await dataSourceStore.fetchDataSource(source.id)
  }
}
</script>

<template>
  <div class="data-source-panel h-full flex flex-col bg-slate-50">
    <!-- Add New Source Button -->
    <div v-if="!isAddingSource" class="p-4 border-b border-slate-200 bg-white">
      <Button
        @click="isAddingSource = true"
        class="w-full flex items-center justify-center space-x-2 bg-primary/10 text-primary hover:bg-primary/20 border border-primary/20"
        variant="ghost"
      >
        <Plus :size="16" />
        <span>Add Data Source</span>
      </Button>
    </div>

    <!-- Add Source Form -->
    <div
      v-if="isAddingSource"
      class="p-4 bg-white border-b border-slate-200 shadow-sm animate-in slide-in-from-top-2 duration-200"
    >
      <div class="flex items-center justify-between mb-3">
        <h3 class="text-sm font-semibold text-slate-800">New API Source</h3>
        <button
          @click="isAddingSource = false"
          class="text-slate-400 hover:text-slate-600 transition-colors"
        >
          <X :size="16" />
        </button>
      </div>

      <div class="space-y-3">
        <div>
          <label class="block text-xs font-medium text-slate-600 mb-1">Name</label>
          <Input
            v-model="newSourceName"
            type="text"
            placeholder="e.g. Users API"
            class="w-full px-2 py-1.5 text-sm"
          />
        </div>
        <div>
          <label class="block text-xs font-medium text-slate-600 mb-1">Endpoint URL</label>
          <div class="flex space-x-1">
            <select
              class="text-xs border border-slate-300 rounded bg-slate-50 px-1 focus:outline-none focus:border-primary"
            >
              <option>GET</option>
            </select>
            <Input
              v-model="newSourceUrl"
              type="text"
              placeholder="https://api..."
              class="flex-1 px-2 py-1.5 text-sm"
            />
          </div>
        </div>

        <!-- Test Actions -->
        <div class="flex items-center space-x-2 pt-2">
          <Button
            @click="handleTestApi"
            :disabled="testStatus === 'loading'"
            class="flex-1 flex items-center justify-center space-x-1 py-1.5 bg-slate-800 text-white hover:bg-slate-900 text-xs font-medium disabled:opacity-50"
          >
            <span v-if="testStatus === 'loading'" class="animate-spin">...</span>
            <Play v-else :size="12" />
            <span>Test Request</span>
          </Button>
          <Button
            @click="handleSaveSource"
            :disabled="!testResult || !newSourceName"
            class="flex-1 flex items-center justify-center space-x-1 py-1.5 bg-primary text-white hover:bg-primary/90 text-xs font-medium disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Save :size="12" />
            <span>Save Source</span>
          </Button>
        </div>

        <!-- Test Result -->
        <div v-if="testResult" class="mt-3">
          <div class="flex items-center space-x-1 mb-1">
            <CheckCircle
              v-if="testStatus === 'success'"
              :size="12"
              class="text-green-500"
            />
            <AlertCircle
              v-else
              :size="12"
              class="text-red-500"
            />
            <span class="text-xs font-medium text-slate-600">Response Preview</span>
          </div>
          <div class="bg-slate-900 rounded p-2 overflow-hidden">
            <pre class="text-[10px] text-green-400 font-mono overflow-auto max-h-32">{{
              JSON.stringify(testResult, null, 2)
            }}</pre>
          </div>
        </div>
      </div>
    </div>

    <!-- Source List -->
    <div class="flex-1 overflow-y-auto p-4 space-y-3">
      <div
        v-if="Object.keys(dataSourceStore.dataSources).length === 0 && !isAddingSource"
        class="text-center py-8 text-slate-400"
      >
        <Database :size="32" class="mx-auto mb-2 opacity-50" />
        <p class="text-sm">No data sources yet.</p>
      </div>

      <div
        v-for="ds in Object.values(dataSourceStore.dataSources)"
        :key="ds.id"
        class="bg-white border border-slate-200 rounded-lg p-3 hover:shadow-sm transition-shadow"
      >
        <div class="flex items-center justify-between mb-2">
          <div class="flex items-center space-x-2">
            <div class="w-2 h-2 rounded-full bg-green-500"></div>
            <span class="font-medium text-sm text-slate-800">{{ ds.name }}</span>
          </div>
          <span
            class="text-[10px] font-mono bg-slate-100 text-slate-500 px-1.5 py-0.5 rounded"
          >
            {{ (ds.config as ApiDataSourceConfig).method }}
          </span>
        </div>
        <div
          class="text-xs text-slate-500 truncate mb-2 font-mono"
          :title="(ds.config as ApiDataSourceConfig).url"
        >
          {{ (ds.config as ApiDataSourceConfig).url }}
        </div>
        <div class="flex justify-end">
          <Button
            @click="handleRunSource(ds)"
            variant="ghost"
            class="text-xs text-primary hover:underline flex items-center space-x-1 h-auto p-0"
          >
            <Play :size="10" />
            <span>Run</span>
          </Button>
        </div>
      </div>
    </div>
  </div>
</template>

// app/src/demo/DataSourcePanel.tsx
import React, { useState } from 'react';
import * as Icons from '../Icons';
import { ComponentData, ApiDefinition } from '../../types';
import { useEditorStore } from '../../store';
import { clsx } from 'clsx';
import { ApiForm } from './ApiForm';

const TestResult = ({ result, onClose }: { result: any, onClose: () => void }) => (
    <div className="fixed inset-0 z-[100] flex items-center justify-center pointer-events-none p-8">
        <div className="bg-white rounded-lg shadow-2xl border border-slate-200 w-[500px] max-h-[80vh] flex flex-col pointer-events-auto animate-in zoom-in-95 fade-in duration-200">
            <div className="flex items-center justify-between px-4 py-3 border-b border-slate-100 bg-slate-50 rounded-t-lg">
                <span className="text-sm font-semibold text-slate-800 flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-emerald-500"></div> API Response
                </span>
                <button onClick={onClose}><Icons.Plus size={18} className="rotate-45 text-slate-400 hover:text-slate-600"/></button>
            </div>
            <div className="p-0 overflow-hidden flex-1 flex flex-col">
                <div className="bg-slate-900 flex-1 overflow-auto p-4">
                     <pre className="font-mono text-xs text-emerald-400 leading-relaxed">{JSON.stringify(result, null, 2)}</pre>
                </div>
            </div>
        </div>
    </div>
);

export const DataSourcePanel = () => {
    const components = useEditorStore(state => state.components);
    const selectComponent = useEditorStore(state => state.selectComponent);
    const apis = useEditorStore(state => state.apis);
    const addApi = useEditorStore(state => state.addApi);
    const updateApi = useEditorStore(state => state.updateApi);
    const deleteApi = useEditorStore(state => state.deleteApi);

    const [isEditing, setIsEditing] = useState<string | null>(null); // 'new' or ID
    const [testResult, setTestResult] = useState<any>(null);

    // 1. Scan for Variables (Inputs)
    const variables = (Object.values(components) as ComponentData[]).filter(c => 
        ['Input', 'Checkbox'].includes(c.type)
    ).map(c => {
        const name = c.properties.flatMap(p => p.items).find(i => i.id === 'name')?.value || 'unknown';
        return { id: c.id, name, type: c.type, componentName: c.name };
    });

    const systemVars = ['user.name', 'user.email', 'system.date'];

    const handleRunTest = async (api: ApiDefinition) => {
        // Simulating Fetch with Request Details
        const requestPreview = {
            url: api.url,
            method: api.method,
            headers: api.headers?.reduce((acc, h) => ({...acc, [h.key]: h.value}), {}),
            params: api.params?.reduce((acc, p) => ({...acc, [p.key]: p.value}), {}),
            body: api.body ? JSON.parse(api.body || '{}') : undefined
        };

        const mockResponse = {
            status: 200,
            statusText: "OK",
            data: api.method === 'GET' 
                ? { results: [{ id: 1, name: "Item A" }, { id: 2, name: "Item B" }], meta: { page: 1 } }
                : { success: true, message: "Resource created", id: "new_123" },
            _debug_request: requestPreview // For user to see what was sent
        };
        
        // Simulate network delay
        setTimeout(() => setTestResult(mockResponse), 800);
    };

    return (
        <div className="relative h-full flex flex-col">
            {/* Editing Overlay */}
            {isEditing && (
                <ApiForm 
                    api={apis.find(a => a.id === isEditing) || (isEditing === 'new' ? undefined : undefined)}
                    onSave={(a) => { 
                        if (isEditing === 'new') addApi(a as any);
                        else updateApi(isEditing, a);
                        setIsEditing(null); 
                    }} 
                    onCancel={() => setIsEditing(null)} 
                />
            )}

            {testResult && <TestResult result={testResult} onClose={() => setTestResult(null)} />}

            <div className="p-4 space-y-6 flex-1 overflow-y-auto">
                {/* Variables Section */}
                <div>
                    <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3 flex items-center gap-2">
                        <Icons.Braces size={12} /> Page Variables
                    </h3>
                    <div className="space-y-2">
                        {variables.length === 0 && <div className="text-xs text-slate-400 italic px-2">No inputs defined yet.</div>}
                        {variables.map(v => (
                            <div 
                                key={v.id} 
                                onClick={() => selectComponent(v.id)}
                                className="flex items-center justify-between p-2 bg-slate-50 border border-slate-100 rounded-md hover:border-primary-300 hover:bg-white hover:shadow-sm cursor-pointer transition-all group"
                            >
                                <div className="flex items-center gap-2 overflow-hidden">
                                    <Icons.TextCursor size={14} className="text-slate-400 group-hover:text-primary-500" />
                                    <div className="flex flex-col min-w-0">
                                        <span className="text-xs font-mono font-medium text-slate-700 truncate text-ellipsis">{`{{${v.name}}}`}</span>
                                        <span className="text-[10px] text-slate-400 truncate">Source: {v.componentName}</span>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* API Section */}
                <div>
                    <div className="flex items-center justify-between mb-3">
                        <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider flex items-center gap-2">
                            <Icons.Globe size={12} /> API Integrations
                        </h3>
                        <button onClick={() => setIsEditing('new')} className="p-1 hover:bg-slate-100 rounded text-slate-500 hover:text-indigo-600 transition-colors">
                            <Icons.Plus size={14} />
                        </button>
                    </div>

                    <div className="space-y-2">
                        {apis.length === 0 && <div className="text-xs text-slate-400 italic px-2">No APIs defined.</div>}
                        
                        {apis.map(api => (
                            <div 
                                key={api.id}
                                className="p-3 bg-white border border-slate-200 rounded-lg shadow-sm hover:shadow-md hover:border-indigo-300 transition-all group relative"
                            >
                                <div className="flex items-center justify-between mb-2">
                                    <div className="flex items-center gap-2">
                                        <span className={clsx(
                                            "text-[10px] font-bold px-1.5 py-0.5 rounded uppercase tracking-wide",
                                            api.method === 'GET' && "bg-blue-50 text-blue-600",
                                            api.method === 'POST' && "bg-purple-50 text-purple-600",
                                            api.method === 'PUT' && "bg-orange-50 text-orange-600",
                                            api.method === 'DELETE' && "bg-red-50 text-red-600"
                                        )}>
                                            {api.method}
                                        </span>
                                        <span className="text-sm font-medium text-slate-800">{api.name}</span>
                                    </div>
                                    <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                        <button onClick={() => handleRunTest(api)} className="p-1.5 text-emerald-500 hover:bg-emerald-50 rounded transition-colors" title="Test API">
                                            <Icons.Play size={14} fill="currentColor" />
                                        </button>
                                        <button onClick={() => setIsEditing(api.id)} className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded transition-colors" title="Edit">
                                            <Icons.Settings size={14} />
                                        </button>
                                        <button onClick={() => deleteApi(api.id)} className="p-1.5 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded transition-colors" title="Delete">
                                            <Icons.Trash2 size={14} />
                                        </button>
                                    </div>
                                </div>
                                <div className="flex items-center gap-2 pl-1">
                                    <Icons.Link size={12} className="text-slate-300 shrink-0" />
                                    <span className="text-xs font-mono text-slate-500 truncate w-full leading-none" title={api.url}>{api.url}</span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* System Vars */}
                <div>
                    <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3 flex items-center gap-2">
                        <Icons.Server size={12} /> System Globals
                    </h3>
                    <div className="space-y-1">
                        {systemVars.map(v => (
                            <div key={v} className="flex items-center gap-2 px-2 py-1.5 rounded hover:bg-slate-50">
                                <Icons.Database size={12} className="text-slate-300" />
                                <span className="text-xs font-mono text-slate-500">{`{{${v}}}`}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};
